Задания 1.1-1.5
js-tasks-ru/jsbasic-20210906-2_xsanka pull request #2
Opened 2021-09-12 18:37 UTC by xsenia

2021-09-12 18:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-13 19:55 UTC, SinimaWath requested changes

2021-09-13 19:55 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Давай используем метод: `includes(' ')` - Он делает тоже самое, но вместо тебя

2021-09-13 19:55 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    console.log(2, name);
Давай уберем из всех задач console.log

2021-09-13 19:55 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if ( lowStr.includes('1xbet') || lowStr.includes('xxx') ) {
lowStr.includes('1xbet') || lowStr.includes('xxx') - результат операции уже boolean, поэтому можно обойтись без if, а сразу вернуть результат

`return lowStr.includes('1xbet') || lowStr.includes('xxx')`

2021-09-15 18:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-15 18:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-15 19:32 UTC, SinimaWath approved these changes
Все круто

2021-09-15 19:33 UTC, merged